name: Update README

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes.
  workflow_dispatch:


jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@v0.3.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "Updated README with recent activity"
          MAX_LINES: 10